version: '3.3'
services:
    receiver:
        container_name: 'rxc'
        privileged: true
        networks:
            - vale
        volumes:
            - '/dev:/dev'
            - '/lib/modules:/lib/modules'
        image: sergiogimenez/netmap-docker:latest
        # command: pkt-gen -i eth0 -f rx
        command: tail -F anything

    # sender:
    #     container_name: 'txc'
    #     privileged: true
    #     networks:
    #         - netmap-net
    #     volumes:
    #         - '/dev:/dev'
    #         - '/lib/modules:/lib/modules'
    #     image: sergiogimenez/netmap-docker:latest
    #     # command: pkt-gen -i eth0 -f tx
    #     command: tail -F anything

networks:
    vale:
        driver: sergiogimenez/vale:latest
